{% set version = "7.2.5" %}

package:
  name: sphinx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx/sphinx-{{ version }}.tar.gz
  sha256: 1a9290001b75c497fd087e92b0334f1bbfa1a1ae7fddc084990c4b7bd1130b88

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  host:
    - python >=3.9
    - pip
    - babel
    - flit-core >=3.7
  run:
    - python >=3.9
    - alabaster >=0.7,<0.8
    - babel >=2.9
    - docutils >=0.18.1,<0.21
    - imagesize >=1.3
    - importlib-metadata >=4.8
    - jinja2 >=3.0
    - packaging >=21.0
    - pygments >=2.14
    - requests >=2.25.0
    - snowballstemmer >=2.0
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp >=2.0.0
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml >=1.1.9
    # only _strictly_ a windows dependency, but appeases `pip check`
    - colorama >=0.4.5

test:
  imports:
    - sphinx
    - sphinx.builders
  requires:
    - pip
  commands:
    - pip check
    - sphinx-quickstart --version

about:
  home: https://www.sphinx-doc.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Sphinx makes it easy to create intelligent and beautiful documentation.
  description: |
    Sphinx makes it easy to create intelligent and beautiful documentation.

    Sphinx uses reStructuredText as its markup language, and many of its strengths
    come from the power and straightforwardness of reStructuredText and its parsing
    and translating suite, the Docutils.
  doc_url: https://www.sphinx-doc.org/en/master/
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - AA-Turner
    - blink1073
    - ccordoba12
    - chohner
    - jakirkham
    - matthiasdiener
    - ocefpaf
