{% set python_min = "3.11" %}
{% set version = "9.0.4" %}

package:
  name: sphinx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx/sphinx-{{ version }}.tar.gz
  sha256: 594ef59d042972abbc581d8baa577404abe4e6c3b04ef61bd7fc2acbd51f3fa3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - babel
    - flit-core >=3.11
  run:
    - roman-numerals >=1.0.0
    - python >={{ python_min }}
    - alabaster >=0.7.14
    - babel >=2.13
    - docutils >=0.20,<0.23
    - imagesize >=1.3
    - jinja2 >=3.1
    - packaging >=23.0
    - pygments >=2.17
    - requests >=2.30.0
    - snowballstemmer >=2.2
    - sphinxcontrib-applehelp >=1.0.7
    - sphinxcontrib-devhelp >=1.0.6
    - sphinxcontrib-htmlhelp >=2.0.6
    - sphinxcontrib-jsmath >=1.0.1
    - sphinxcontrib-qthelp >=1.0.6
    - sphinxcontrib-serializinghtml >=1.1.9
    # only _strictly_ a windows dependency, but appeases `pip check`
    - colorama >=0.4.6

test:
  imports:
    - sphinx
    - sphinx.builders
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - sphinx-build --help
    - sphinx-quickstart --version

about:
  home: https://www.sphinx-doc.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: Sphinx makes it easy to create intelligent and beautiful documentation.
  description: |
    Sphinx makes it easy to create intelligent and beautiful documentation.

    Sphinx uses reStructuredText as its markup language, and many of its strengths
    come from the power and straightforwardness of reStructuredText and its parsing
    and translating suite, the Docutils.
  doc_url: https://www.sphinx-doc.org/en/master/
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - AA-Turner
    - blink1073
    - jakirkham
    - matthiasdiener
    - ocefpaf
