{% set version = "7.4.3" %}

package:
  name: sphinx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx/sphinx-{{ version }}.tar.gz
  sha256: bd846bcb09fd2b6e94ce3e1ad50f4618bccf03cc7c17d0f3fa87393c0bd9178b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  host:
    - python >=3.9
    - pip
    - babel
    - flit-core >=3.7
  run:
    - python >=3.9
    - alabaster >=0.7.14,<0.8.dev0
    - babel >=2.13
    - docutils >=0.20,<0.22
    - imagesize >=1.3
    - importlib-metadata >=6.0
    - jinja2 >=3.1
    - packaging >=23.0
    - pygments >=2.17
    - requests >=2.30.0
    - tomli >=2.0
    - snowballstemmer >=2.2
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp >=2.0.0
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml >=1.1.9
    # only _strictly_ a windows dependency, but appeases `pip check`
    - colorama >=0.4.6

test:
  imports:
    - sphinx
    - sphinx.builders
  requires:
    - pip
  commands:
    - pip check
    - sphinx-build --help
    - sphinx-quickstart --version

about:
  home: https://www.sphinx-doc.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: Sphinx makes it easy to create intelligent and beautiful documentation.
  description: |
    Sphinx makes it easy to create intelligent and beautiful documentation.

    Sphinx uses reStructuredText as its markup language, and many of its strengths
    come from the power and straightforwardness of reStructuredText and its parsing
    and translating suite, the Docutils.
  doc_url: https://www.sphinx-doc.org/en/master/
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - AA-Turner
    - blink1073
    - ccordoba12
    - jakirkham
    - matthiasdiener
    - ocefpaf
