{% set version = "5.0.0" %}

package:
  name: sphinx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Sphinx/Sphinx-{{ version }}.tar.gz
  sha256: 464d9c1bd5613bcebe76b46658763f3f3dbb184da7406e632a84596d3cd8ee90

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  host:
    - python >=3.6
    - pip
    - babel
  run:
    - python >=3.6
    - alabaster >=0.7,<0.8
    - babel >=1.3
    - docutils >=0.14,<0.19
    - imagesize
    - importlib-metadata >=4.4
    - jinja2 >=2.3
    - packaging
    - pygments >=2.0
    - python
    - requests >=2.5.0
    - snowballstemmer >=1.1
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp >=2.0.0
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml >=1.1.5
    # only _strictly_ a windows dependency, but appeases `pip check`
    - colorama >=0.3.5

test:
  imports:
    - sphinx
    - sphinx.builders
  requires:
    - pip
  commands:
    - pip check
    - sphinx-quickstart --version

about:
  home: https://www.sphinx-doc.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Sphinx is a tool that makes it easy to create intelligent and beautiful documentation
  description: |
    Sphinx is a tool that makes it easy to create intelligent and beautiful documentation,
    written by Georg Brandl and licensed under the BSD license.
    It was originally created for the new Python documentation, and it has excellent
    facilities for the documentation of Python projects, but C/C++ is already supported
    as well, and it is planned to add special support for other languages as well.
  doc_url: https://www.sphinx-doc.org/en/stable/contents.html
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - chohner
    - jakirkham
    - ocefpaf
    - blink1073
    - ccordoba12
