{% set version = "1.7.4" %}

package:
  name: sphinx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Sphinx/Sphinx-{{ version }}.tar.gz
  sha256: e9b1a75a3eae05dded19c80eb17325be675e0698975baae976df603b6ed1eb10

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - jinja2
    - pygments
    - docutils
    - snowballstemmer
    - babel
    - alabaster
    - imagesize
    - requests
    - typing
    - sphinxcontrib-websupport
    - packaging

test:
  commands:
    - sphinx-quickstart --version

about:
  home: http://www.sphinx-doc.org
  license: BSD 2-clause
  summary: 'Sphinx is a tool that makes it easy to create intelligent and beautiful documentation'
  description: |
    Sphinx is a tool that makes it easy to create intelligent and beautiful documentation,
    written by Georg Brandl and licensed under the BSD license.
    It was originally created for the new Python documentation, and it has excellent
    facilities for the documentation of Python projects, but C/C++ is already supported
    as well, and it is planned to add special support for other languages as well.
  doc_url: http://www.sphinx-doc.org/en/stable/contents.html
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - chohner
    - jakirkham
