build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
provider:
  linux: azure
  linux_aarch64: default
  linux_ppc64le: default
  osx: azure
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
